In [1]:
import numpy as np

In [2]:
array_nd = np.arange(6)

array_nd

array([0, 1, 2, 3, 4, 5])

In [3]:
array_nd.shape

(6,)

In [ ]:
# converting array share always depends on the number of elements in it.
# shape can be converted if the total number of elements in result array should match with the old one.

In [ ]:
# in previous 6 elements exists. If we have to convert them then we have the option that either 2*3 or 3*2

In [4]:
array_nd = np.arange(6).reshape(2,3)
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
*** If we use the same variable for multiple times then the recent executed result will be saved to the variable

In [8]:
array_nd = np.arange(6).reshape(2,4)
array_nd

ValueError: cannot reshape array of size 6 into shape (2,4)

In [ ]:
*** Always result of rows * columns should match the number of elements in arange ***

In [9]:
array_nd = np.arange(6).reshape(3,2)
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
array_nd.shape

(3, 2)

In [12]:
array_ones =np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
# above statement is printing the ones in the shapre of existing array

In [13]:
# Printing array:

a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [14]:
b = np.arange(12).reshape(4,3) # (rows,cols)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
*** reshaping the array is nothing but segretating the elements ***

In [15]:
# Basic Numpy operations:-

a = np.array([10,10,10])

In [16]:
b = np.array([5,5,5])

In [17]:
a+b

array([15, 15, 15])

In [18]:
a-b

array([5, 5, 5])

In [19]:
a*b

array([50, 50, 50])

In [20]:
a/b

array([2., 2., 2.])

In [21]:
# comparision operator:

a<35

array([ True,  True,  True])

In [22]:
a >25

array([False, False, False])

In [ ]:
**** always mathematical calculations will be element wise operarion ****

In [23]:
# Universal function in Numpy:- 

angles =np.array([0,30,45,60,75,90])
angles

array([ 0, 30, 45, 60, 75, 90])

In [ ]:
# converting degrees to radians

In [26]:
angles_radians = angles*np.pi/180
angles_radians

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.30899694,
       1.57079633])

In [28]:
angles_radians1 = np.radians(angles)
angles_radians1

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.30899694,
       1.57079633])