In [ ]:
Data Analytics in python:
    
    1. Numpy
    2. Pandas
    3. matplotlib
    
    4. scipy  -- along with numpy advanced features
    
    These are seprate libraries, if we are using normal python.
    if we use jupyter then all are integrated

In [1]:
# 1. Numpy:- 
# how to install numpy
!pip install numpy 

In [2]:
!pip install numpy --upgrade

  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\compat\\py3k.py'
Consider using the `--user` option or check the permissions.



In [ ]:
# Matrices:

Numpy is multi dimensional array.

what is numpy?
    - it is Numerical computations
    - machine Learning, Deep learning, AI and other Analytics
    Numpy ---> forms the foundational layer to all !!!!
    
0 & 1  --> binary system


Numpy array  ---- similar to python lists


***** 1. can you please explain the diffence between numpy array & lists
       2. which one to use for getting better results
    
    list is giving the output in 1 min
    numpy will give output in 2 secs.
    
    List --- it completely maintains order & evaluates everything inside it.
    Numpy  --- it will evaluates the actual required components
    

In [3]:
import numpy as np

In [4]:
array_one = np.array([1,2,3,4])   # single dimensional array

array_one

array([1, 2, 3, 4])

In [5]:
type(array_one)

numpy.ndarray

In [ ]:
# ndarray    ---> n dimensional array

In [6]:
numbers = [9,8,7,6]
array_two =np.array(numbers)
array_two

array([9, 8, 7, 6])

In [9]:
array_of_zeros =np.zeros((3,4))   # 3 rows & 4 columns -- 3*4 matrix

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
array_of_ones = np.ones((2,3))

array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
array_of_ones =np.one((2,3), dtype=np.int16)

array_of_ones

AttributeError: module 'numpy' has no attribute 'one'

In [12]:
array_of_ones =np.one((2,3), dtype=np.int16)

array_of_one

AttributeError: module 'numpy' has no attribute 'one'

In [13]:
array_of_ones = np.ones((2,3), dtype=np.int16)

array_of_ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)