In [ ]:
import numpy as np

In [1]:
array_empty = np.empty((2,3))

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
array_empty = np.empty((2,3))

array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [1]:
array_eye = np.eye(3)

array_eye

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [5]:
array_eye = np.eye(3)

array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
array_of_events = np.arange(2,20,2)   # printing even numbers

array_of_events

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
array_of_events = np.arange(3,20,1)

array_of_events

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
array_of_events = np.arange(3,20,2)

array_of_events

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
array_of_floats = np.arange(0,3,0.3)

array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [ ]:
*** variable name should not contain spaces ***** 

In [10]:
# how to create a 2 dimensional array:-

array_2d = np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [11]:
# how to find the array shape
array_2d.shape

(2, 3)

In [ ]:
*** array will be float type when we use inbuilt libraries ****

In [12]:
array.arange(6)

NameError: name 'array' is not defined

In [15]:
array.arange(6)

NameError: name 'array' is not defined

In [ ]:
# I am getting error while run the above statement